---
docker_kernel_min_version: '0'

# https://yum.dockerproject.org/repo/main/centos/7/Packages/
# or do 'yum --showduplicates list docker-engine'
docker_versioned_pkg:
  'latest': docker-engine
  '1.11': docker-engine-1.11.2-1.el7.centos
  '1.12': docker-engine-1.12.6-1.el7.centos
  '1.13': docker-engine-1.13.1-1.el7.centos
  '18.09.0': docker-ce-18.09.0-3.el7.x86_64  
  '17.03': docker-ce-17.03.3.ce-1.el7
  '17.09': docker-ce-17.09.1.ce-1.el7.centos
  '17.12': docker-ce-17.12.1.ce-1.el7.centos
  '18.03': docker-ce-18.03.1.ce-1.el7.centos
  '18.06': docker-ce-18.06.3.ce-3.el7
  '18.09': docker-ce-18.09.9-3.el7
  '19.03': docker-ce-19.03.8-3.el7
  'stable': docker-ce-18.09.9-3.el7
  'edge': docker-ce-19.03.8-3.el7

# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
# https://download.docker.com/linux/centos/7/x86_64/stable/Packages/

docker_package_info:
  pkg_mgr: yum
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"

docker_repo_key_info:
  pkg_key: ''
  repo_keys: []

docker_repo_info:
  pkg_repo: ''
  repos: []
