---
# Flannel public IP
# The address that flannel should advertise as how to access the system
# Disabled until https://github.com/coreos/flannel/issues/712 is fixed
# flannel_public_ip: "{{ access_ip|default(ip|default(ansible_default_ipv4.address)) }}"

## interface that should be used for flannel operations
## This is actually an inventory node-level item
# flannel_interface:

# You can choose what type of flannel backend to use
# please refer to flannel's docs : https://github.com/coreos/flannel/blob/master/README.md
flannel_backend_type: "vxlan"

# Limits for apps
flannel_memory_limit: 500M
flannel_cpu_limit: 300m
flannel_memory_requests: 64M
flannel_cpu_requests: 150m

# Legacy directory, will be removed if found.
flannel_cert_dir: /etc/flannel/certs

# ipsec default settings

# Forces the use UDP encapsulation of packets which can help with some NAT gateways.
flannel_ipsec_udpencap: false

# The pre shared key to use. It needs to be at least 96 characters long.
#  One method for generating this key is to run `dd if=/dev/urandom count=48 bs=1 status=none | xxd -p -c 48`
# flannel_ipsec_psk

# Change this string to choose another ESP Proposal.
flannel_ipsec_espproposal: "aes128gcm16-sha256-prfsha256-ecp256"